title: Testing training
theme: minima
author: Michael G
email: blabla@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Testy test tester

# social links
twitter_username: pixiedust1337 # DO NOT include the @ character, or else the build will fail!
github_username: MickQG # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
